services:
  spdaze:
    image: itzg/minecraft-server:latest
    pull_policy: latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: |
        fabric-api
      MODE: "survival"
      LEVEL: "SPdaze"
      ENABLE_WHITELIST: TRUE
    restart: on-failure:3